package com.duzon.lulu.auto.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.duzon.lulu.auto.model.TCalendar;
import com.duzon.lulu.auto.model.TCalendarExample;

public interface TCalendarMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_calendar
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	long countByExample(TCalendarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_calendar
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	int deleteByExample(TCalendarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_calendar
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	int deleteByPrimaryKey(Long calendar_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_calendar
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	int insert(TCalendar record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_calendar
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	int insertSelective(TCalendar record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_calendar
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	List<TCalendar> selectByExample(TCalendarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_calendar
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	TCalendar selectByPrimaryKey(Long calendar_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_calendar
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	int updateByExampleSelective(@Param("record") TCalendar record, @Param("example") TCalendarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_calendar
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	int updateByExample(@Param("record") TCalendar record, @Param("example") TCalendarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_calendar
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	int updateByPrimaryKeySelective(TCalendar record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_calendar
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	int updateByPrimaryKey(TCalendar record);
}