package com.duzon.lulu.auto.mapper;

import com.duzon.lulu.auto.model.TestCompany;
import com.duzon.lulu.auto.model.TestCompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestCompanyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_company
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	long countByExample(TestCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_company
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	int deleteByExample(TestCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_company
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	int deleteByPrimaryKey(String company_code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_company
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	int insert(TestCompany record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_company
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	int insertSelective(TestCompany record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_company
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	List<TestCompany> selectByExample(TestCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_company
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	TestCompany selectByPrimaryKey(String company_code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_company
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	int updateByExampleSelective(@Param("record") TestCompany record, @Param("example") TestCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_company
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	int updateByExample(@Param("record") TestCompany record, @Param("example") TestCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_company
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	int updateByPrimaryKeySelective(TestCompany record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_company
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	int updateByPrimaryKey(TestCompany record);
}