package com.duzon.lulu.auto.model;

import java.util.Date;

public class TCalendar {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_calendar.calendar_id
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	private Long calendar_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_calendar.calendar_name
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	private String calendar_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_calendar.reg_id
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	private String reg_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_calendar.reg_date
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	private Date reg_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_calendar.upt_id
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	private String upt_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_calendar.useyn
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	private String useyn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_calendar.upt_date
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	private Date upt_date;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_calendar.calendar_id
	 * @return  the value of t_calendar.calendar_id
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	public Long getCalendar_id() {
		return calendar_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_calendar.calendar_id
	 * @param calendar_id  the value for t_calendar.calendar_id
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	public void setCalendar_id(Long calendar_id) {
		this.calendar_id = calendar_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_calendar.calendar_name
	 * @return  the value of t_calendar.calendar_name
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	public String getCalendar_name() {
		return calendar_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_calendar.calendar_name
	 * @param calendar_name  the value for t_calendar.calendar_name
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	public void setCalendar_name(String calendar_name) {
		this.calendar_name = calendar_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_calendar.reg_id
	 * @return  the value of t_calendar.reg_id
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	public String getReg_id() {
		return reg_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_calendar.reg_id
	 * @param reg_id  the value for t_calendar.reg_id
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	public void setReg_id(String reg_id) {
		this.reg_id = reg_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_calendar.reg_date
	 * @return  the value of t_calendar.reg_date
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	public Date getReg_date() {
		return reg_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_calendar.reg_date
	 * @param reg_date  the value for t_calendar.reg_date
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	public void setReg_date(Date reg_date) {
		this.reg_date = reg_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_calendar.upt_id
	 * @return  the value of t_calendar.upt_id
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	public String getUpt_id() {
		return upt_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_calendar.upt_id
	 * @param upt_id  the value for t_calendar.upt_id
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	public void setUpt_id(String upt_id) {
		this.upt_id = upt_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_calendar.useyn
	 * @return  the value of t_calendar.useyn
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	public String getUseyn() {
		return useyn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_calendar.useyn
	 * @param useyn  the value for t_calendar.useyn
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	public void setUseyn(String useyn) {
		this.useyn = useyn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_calendar.upt_date
	 * @return  the value of t_calendar.upt_date
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	public Date getUpt_date() {
		return upt_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_calendar.upt_date
	 * @param upt_date  the value for t_calendar.upt_date
	 * @mbg.generated  Tue Jul 13 14:39:50 KST 2021
	 */
	public void setUpt_date(Date upt_date) {
		this.upt_date = upt_date;
	}
}