package com.duzon.lulu.auto.model;

public class TestCompany {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_company.company_code
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	private String company_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_company.company_name
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	private String company_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_company.company_type
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	private String company_type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_company.business_type
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	private String business_type;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_company.company_code
	 * @return  the value of test_company.company_code
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	public String getCompany_code() {
		return company_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_company.company_code
	 * @param company_code  the value for test_company.company_code
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	public void setCompany_code(String company_code) {
		this.company_code = company_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_company.company_name
	 * @return  the value of test_company.company_name
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	public String getCompany_name() {
		return company_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_company.company_name
	 * @param company_name  the value for test_company.company_name
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	public void setCompany_name(String company_name) {
		this.company_name = company_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_company.company_type
	 * @return  the value of test_company.company_type
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	public String getCompany_type() {
		return company_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_company.company_type
	 * @param company_type  the value for test_company.company_type
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	public void setCompany_type(String company_type) {
		this.company_type = company_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_company.business_type
	 * @return  the value of test_company.business_type
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	public String getBusiness_type() {
		return business_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_company.business_type
	 * @param business_type  the value for test_company.business_type
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	public void setBusiness_type(String business_type) {
		this.business_type = business_type;
	}
}