package com.duzon.lulu.auto.model;

public class TestUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_user.id
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_user.pw
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	private String pw;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_user.name
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_user.company_code
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	private String company_code;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_user.id
	 * @return  the value of test_user.id
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_user.id
	 * @param id  the value for test_user.id
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_user.pw
	 * @return  the value of test_user.pw
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	public String getPw() {
		return pw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_user.pw
	 * @param pw  the value for test_user.pw
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	public void setPw(String pw) {
		this.pw = pw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_user.name
	 * @return  the value of test_user.name
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_user.name
	 * @param name  the value for test_user.name
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_user.company_code
	 * @return  the value of test_user.company_code
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	public String getCompany_code() {
		return company_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_user.company_code
	 * @param company_code  the value for test_user.company_code
	 * @mbg.generated  Thu Oct 13 16:52:32 KST 2016
	 */
	public void setCompany_code(String company_code) {
		this.company_code = company_code;
	}
}