package com.duzon.lulu.auto.model;

import java.util.Date;

public class TSchedule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule.schedule_id
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    private Long schedule_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule.start_time
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    private Date start_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule.end_time
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    private Date end_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule.attend_num
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    private Long attend_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule.schedule_desc
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    private String schedule_desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule.schedule_place
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    private String schedule_place;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule.schedule_name
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    private String schedule_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule.useyn
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    private String useyn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule.reg_id
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    private String reg_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule.reg_date
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    private Date reg_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule.upt_id
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    private String upt_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule.upt_date
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    private Date upt_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule.calendar_id
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    private Long calendar_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule.schedule_id
     *
     * @return the value of t_schedule.schedule_id
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    public Long getSchedule_id() {
        return schedule_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule.schedule_id
     *
     * @param schedule_id the value for t_schedule.schedule_id
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    public void setSchedule_id(Long schedule_id) {
        this.schedule_id = schedule_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule.start_time
     *
     * @return the value of t_schedule.start_time
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    public Date getStart_time() {
        return start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule.start_time
     *
     * @param start_time the value for t_schedule.start_time
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    public void setStart_time(Date start_time) {
        this.start_time = start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule.end_time
     *
     * @return the value of t_schedule.end_time
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    public Date getEnd_time() {
        return end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule.end_time
     *
     * @param end_time the value for t_schedule.end_time
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    public void setEnd_time(Date end_time) {
        this.end_time = end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule.attend_num
     *
     * @return the value of t_schedule.attend_num
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    public Long getAttend_num() {
        return attend_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule.attend_num
     *
     * @param attend_num the value for t_schedule.attend_num
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    public void setAttend_num(Long attend_num) {
        this.attend_num = attend_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule.schedule_desc
     *
     * @return the value of t_schedule.schedule_desc
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    public String getSchedule_desc() {
        return schedule_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule.schedule_desc
     *
     * @param schedule_desc the value for t_schedule.schedule_desc
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    public void setSchedule_desc(String schedule_desc) {
        this.schedule_desc = schedule_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule.schedule_place
     *
     * @return the value of t_schedule.schedule_place
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    public String getSchedule_place() {
        return schedule_place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule.schedule_place
     *
     * @param schedule_place the value for t_schedule.schedule_place
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    public void setSchedule_place(String schedule_place) {
        this.schedule_place = schedule_place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule.schedule_name
     *
     * @return the value of t_schedule.schedule_name
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    public String getSchedule_name() {
        return schedule_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule.schedule_name
     *
     * @param schedule_name the value for t_schedule.schedule_name
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    public void setSchedule_name(String schedule_name) {
        this.schedule_name = schedule_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule.useyn
     *
     * @return the value of t_schedule.useyn
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    public String getUseyn() {
        return useyn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule.useyn
     *
     * @param useyn the value for t_schedule.useyn
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    public void setUseyn(String useyn) {
        this.useyn = useyn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule.reg_id
     *
     * @return the value of t_schedule.reg_id
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    public String getReg_id() {
        return reg_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule.reg_id
     *
     * @param reg_id the value for t_schedule.reg_id
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    public void setReg_id(String reg_id) {
        this.reg_id = reg_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule.reg_date
     *
     * @return the value of t_schedule.reg_date
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    public Date getReg_date() {
        return reg_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule.reg_date
     *
     * @param reg_date the value for t_schedule.reg_date
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    public void setReg_date(Date reg_date) {
        this.reg_date = reg_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule.upt_id
     *
     * @return the value of t_schedule.upt_id
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    public String getUpt_id() {
        return upt_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule.upt_id
     *
     * @param upt_id the value for t_schedule.upt_id
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    public void setUpt_id(String upt_id) {
        this.upt_id = upt_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule.upt_date
     *
     * @return the value of t_schedule.upt_date
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    public Date getUpt_date() {
        return upt_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule.upt_date
     *
     * @param upt_date the value for t_schedule.upt_date
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    public void setUpt_date(Date upt_date) {
        this.upt_date = upt_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule.calendar_id
     *
     * @return the value of t_schedule.calendar_id
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    public Long getCalendar_id() {
        return calendar_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule.calendar_id
     *
     * @param calendar_id the value for t_schedule.calendar_id
     *
     * @mbg.generated Tue Jul 13 14:39:50 KST 2021
     */
    public void setCalendar_id(Long calendar_id) {
        this.calendar_id = calendar_id;
    }
}